
const mobilePhones = [
    {
      key:1,
      images: ["Samsung Galaxy S24 Ultra","Samsung Galaxy S24 Ultra1"],
      title: "Samsung Galaxy S24 Ultra",
      price: "USD $1,299",
      condition: "Brand New",
      color: "Titanium Gray",
      storage: "12GB/1TB",
      brand: "Samsung",
      screenSize: "6.8 inches",
      os: "Android 14",
    },
    { 
      key:2,
      images: ["iPhone 15 Pro Max","iPhone 15 Pro Max1"],
      title: "iPhone 15 Pro Max",
      price: "USD $1,199",
      condition: "Brand New",
      color: "Titanium Blue",
      storage: "8GB/1TB",
      brand: "iPhone",
      screenSize: "6.7 inches",
      os: "iOS 17",
    },
    {
      key:3,
      images: ["Samsung Galaxy Z Fold 5","Samsung Galaxy Z Fold 51"],
      title: "Samsung Galaxy Z Fold 5",
      price: "USD $1,799",
      condition: "Brand New",
      color: "Icy Blue",
      storage: "12GB/1TB",
      brand: "Samsung",
      screenSize: "7.6 inches (Folded: 6.2 inches)",
      os: "Android 13",
    },
    {
      key:4,
      images: ["iPhone 14 Pro Max","iPhone 14 Pro Max1"],
      title: "iPhone 14 Pro Max",
      price: "USD $1,099",
      condition: "Brand New",
      color: "Deep Purple",
      storage: "6GB/1TB",
      brand: "iPhone",
      screenSize: "6.7 inches",
      os: "iOS 16",
    },
    {
      key:5,
      images: ["iPhone 13 Pro Max","iPhone 13 Pro Max1"],
      title: "iPhone 13 Pro Max",
      price: "USD $999",
      condition: "Brand New",
      color: "Sierra Blue",
      storage: "6GB/512GB",
      brand: "iPhone",
      screenSize: "6.7 inches",
      os: "iOS 15",
    },
    {
      key:6,
      images: ["Samsung Galaxy S23 Ultra","Samsung Galaxy S23 Ultra1"],
      title: "Samsung Galaxy S23 Ultra",
      price: "USD $1,199",
      condition: "Brand New",
      color: "Phantom Black",
      storage: "12GB/1TB",
      brand: "Samsung",
      screenSize: "6.8 inches",
      os: "Android 13",
    },
    {
      key:7,
      images: ["iPhone 12 Pro Max","iPhone 12 Pro Max1"],
      title: "iPhone 12 Pro Max",
      price: "USD $799",
      condition: "Used",
      color: "Pacific Blue",
      storage: "6GB/512GB",
      brand: "iPhone",
      screenSize: "6.7 inches",
      os: "iOS 14",
    },
    {
      key:8,
      images: [ "Samsung Galaxy Note 20 Ultra", "Samsung Galaxy Note 20 Ultra1"],
      title: "Samsung Galaxy Note 20 Ultra",
      price: "USD $799",
      condition: "Used",
      color: "Mystic Bronze",
      storage: "8GB/512GB",
      brand: "Samsung",
      screenSize: "6.9 inches",
      os: "Android 11",
    },
    {
      key:9,
      images: ["iPhone 11 Pro Max","iPhone 11 Pro Max1"],
      title: "iPhone 11 Pro Max",
      price: "USD $599",
      condition: "Refurbished",
      color: "Midnight Green",
      storage: "4GB/512GB",
      brand: "iPhone",
      screenSize: "6.5 inches",
      os: "iOS 13",
    }
  ];
  
  export default mobilePhones;